### ISSUE TITLE
新版webpack打包的时候，自己的打包进去的代码就带有很多es5的元素，es5.shim在这些代码的后面，所以ie8内还是会影响执行，es5.shim只能在页面脚本的顶部独立加载，还需更改webpack打包进去的代码

### ISSUE THREAD

**Issue by stevenCJC** [zhoulijie/react-redux-support-ie8#2]
新版webpack打包的时候，自己的打包进去的代码就带有很多es5的元素，es5.shim在这些代码的后面，所以ie8内还是会影响执行，es5.shim只能在页面脚本的顶部独立加载，还需更改webpack打包进去的代码

**Comment by zhoulijie** [comment]
@stevenCJC Nice! 方便提个pr不？

**Comment by herorest** [comment]
![image](https://cloud.githubusercontent.com/assets/2202767/14458832/8fd56d36-00e6-11e6-84e3-768148f936ba.png)

模拟ie8下，还是会报错

**Comment by zhoulijie** [comment]
@herorest 是的，npm run build后IE8下是不影响执行的。或者你可以参考顶楼的思路。这个之后我会修正。多谢提出

**Comment by zhoulijie** [comment]
@stevenCJC @herorest 感谢提出！已修复。
