### ISSUE TITLE
clone后在IE8中运行依然白屏

### ISSUE THREAD

**Issue by cgd199158** [zhoulijie/react-redux-support-ie8#4]
IE显示参数我校，请问下是什么问题？

**Comment by zhoulijie** [comment]
是有这种情况，`npm run build` 之后，其实是不影响的。

**Comment by zhoulijie** [comment]
是有这种情况，但 `npm run build ` 之后，其实是不影响运行的。

**Comment by cgd199158** [comment]
可是我运行npm run build 和npm run build:webpack 后在ie中还是无法显示。是什么原因呢？谢谢！

**Comment by zhoulijie** [comment]
这个我到没碰到过，之前试了几台IE8没什么问题。试着换几台机器看看IE8呢？

**Comment by xkok** [comment]
IE8 下生产模式打包 报错: "function"==typeof Symbol&&Symbol.for&&Symbol.for("react.element"), 缺少标识符, 不知道怎么把for替换["for"]

**Comment by zhoulijie** [comment]
@xkok https://github.com/xcatliu/react-ie8 看看对你有帮助吗

**Comment by ericyang89** [comment]
已解决，详情https://github.com/ericyang89/react-redux-support-ie8

**Comment by ericyang89** [comment]
已提交pr
